#!/usr/bin/env python

import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--file', required=True)
parser.add_argument('--indent', nargs='?', default='2')
parser.add_argument('--type', nargs='?', default='html')
args = parser.parse_args()

processArg = ['js-beautify',
              '-r',
              '-s',
              args.indent,
              '--type',
              args.type,
              '--file',
              args.file,
              ]
processArg = filter(bool, processArg)
subprocess.call(processArg)
